//
//  USDAFoodDatabase.swift
//  calorietracker
//
//  Read-only access to a bundled USDA FoodData Central SQLite database. Used by
//  USDANutritionTool to ground on-device LLM nutrition estimates against
//  ground-truth values, which is the single biggest accuracy lever available
//  to the on-device tier (a 3B-parameter system model will hallucinate exact
//  gram values without it).
//
//  Phase 2 ships the *code only* — the actual `usda_foods.sqlite` file is built
//  by `scripts/fetch_usda.sh` from USDA's public CSV dump and dropped into
//  `calorietracker/Resources/`. The build still succeeds without the file;
//  every method here gracefully returns empty results so the FM session sees
//  "tool unavailable" rather than a crash.
//
//  Schema (created by fetch_usda.sh):
//      CREATE TABLE foods (
//          fdc_id INTEGER PRIMARY KEY,
//          description TEXT NOT NULL,
//          food_category TEXT,
//          kcal_per_100g REAL,
//          protein_per_100g REAL,
//          carbs_per_100g REAL,
//          fat_per_100g REAL,
//          sugar_per_100g REAL,
//          added_sugar_per_100g REAL,
//          fiber_per_100g REAL,
//          sat_fat_per_100g REAL,
//          mono_fat_per_100g REAL,
//          poly_fat_per_100g REAL,
//          cholesterol_mg_per_100g REAL,
//          sodium_mg_per_100g REAL,
//          potassium_mg_per_100g REAL
//      );
//      CREATE VIRTUAL TABLE foods_fts USING fts5(description, content='foods', content_rowid='fdc_id');
//

import Foundation
import SQLite3

/// Read-only handle to the bundled USDA database. Singleton to avoid opening
/// the SQLite file repeatedly — the FM tool can be called multiple times in
/// one generation, and each open/close is non-trivial.
final class USDAFoodDatabase {

    /// Shared singleton. Lazy because the database file may be absent in dev
    /// builds (Phase 2 ships without data); accessing `.shared` does not crash
    /// in that case — `isAvailable` simply returns false.
    static let shared = USDAFoodDatabase()

    private var db: OpaquePointer?
    let isAvailable: Bool

    /// Resource bundle filename for the SQLite database. Generated by
    /// `scripts/fetch_usda.sh` and copied into the app bundle by the
    /// PBXFileSystemSynchronizedRootGroup machinery (any non-source file in
    /// the `calorietracker/` tree is auto-bundled by Xcode 16+).
    private static let resourceName = "usda_foods"
    private static let resourceExtension = "sqlite"

    /// Opens the bundled DB read-only. Failing to find or open the file is
    /// non-fatal: every public method below handles `db == nil` by returning
    /// empty results. This keeps the app shippable while the fetch script is
    /// run on a developer's machine before each release.
    private init() {
        guard let path = Bundle.main.path(forResource: Self.resourceName, ofType: Self.resourceExtension) else {
            self.isAvailable = false
            self.db = nil
            return
        }
        var handle: OpaquePointer?
        let flags = SQLITE_OPEN_READONLY | SQLITE_OPEN_FULLMUTEX
        if sqlite3_open_v2(path, &handle, flags, nil) == SQLITE_OK {
            self.db = handle
            self.isAvailable = true
        } else {
            // Some SQLite errors leave the handle non-nil — close to free its memory.
            sqlite3_close(handle)
            self.db = nil
            self.isAvailable = false
        }
    }

    deinit {
        if let db {
            sqlite3_close(db)
        }
    }

    // MARK: - Public lookup API

    /// Per-100g nutrition row. Mirrors the SQLite schema 1:1 — no transformation
    /// happens at this layer. Scaling to a portion size is done by the caller
    /// (`USDANutritionTool` does it to satisfy the LLM's portion query).
    struct FoodRow: Equatable {
        let fdcId: Int
        let description: String
        let foodCategory: String?
        let kcalPer100g: Double?
        let proteinPer100g: Double?
        let carbsPer100g: Double?
        let fatPer100g: Double?
        let sugarPer100g: Double?
        let addedSugarPer100g: Double?
        let fiberPer100g: Double?
        let satFatPer100g: Double?
        let monoFatPer100g: Double?
        let polyFatPer100g: Double?
        let cholesterolMgPer100g: Double?
        let sodiumMgPer100g: Double?
        let potassiumMgPer100g: Double?
    }

    /// Full-text-search style food lookup. Uses the FTS5 virtual table built
    /// by the fetch script when present; falls back to a `LIKE`-based search
    /// against the main table otherwise. Returns the top `limit` hits ordered
    /// by FTS rank (or alphabetically when LIKE-fallback).
    func search(query: String, limit: Int = 5) -> [FoodRow] {
        guard let db, isAvailable else { return [] }
        let sanitized = sanitizedFTSQuery(query)
        guard !sanitized.isEmpty else { return [] }

        // Try FTS5 first.
        let ftsSQL = """
            SELECT f.fdc_id, f.description, f.food_category,
                   f.kcal_per_100g, f.protein_per_100g, f.carbs_per_100g, f.fat_per_100g,
                   f.sugar_per_100g, f.added_sugar_per_100g, f.fiber_per_100g,
                   f.sat_fat_per_100g, f.mono_fat_per_100g, f.poly_fat_per_100g,
                   f.cholesterol_mg_per_100g, f.sodium_mg_per_100g, f.potassium_mg_per_100g
            FROM foods_fts fts
            JOIN foods f ON f.fdc_id = fts.rowid
            WHERE foods_fts MATCH ?
            ORDER BY rank
            LIMIT ?
        """
        if let rows = runQuery(sql: ftsSQL, bindings: [.text(sanitized), .int(limit)]) {
            return rows
        }

        // FTS table missing or query syntax error — fall back to LIKE.
        let likeSQL = """
            SELECT fdc_id, description, food_category,
                   kcal_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g,
                   sugar_per_100g, added_sugar_per_100g, fiber_per_100g,
                   sat_fat_per_100g, mono_fat_per_100g, poly_fat_per_100g,
                   cholesterol_mg_per_100g, sodium_mg_per_100g, potassium_mg_per_100g
            FROM foods
            WHERE description LIKE ?
            ORDER BY length(description)
            LIMIT ?
        """
        return runQuery(sql: likeSQL, bindings: [.text("%\(query)%"), .int(limit)]) ?? []
    }

    /// Exact lookup by FDC ID. The FM tool can use this to fetch follow-up data
    /// after a search returns multiple candidates and the model picks one.
    func lookup(fdcId: Int) -> FoodRow? {
        guard let db, isAvailable else { return nil }
        let sql = """
            SELECT fdc_id, description, food_category,
                   kcal_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g,
                   sugar_per_100g, added_sugar_per_100g, fiber_per_100g,
                   sat_fat_per_100g, mono_fat_per_100g, poly_fat_per_100g,
                   cholesterol_mg_per_100g, sodium_mg_per_100g, potassium_mg_per_100g
            FROM foods
            WHERE fdc_id = ?
            LIMIT 1
        """
        return runQuery(sql: sql, bindings: [.int(fdcId)])?.first
    }

    // MARK: - Internal SQLite helpers

    private enum Binding {
        case text(String)
        case int(Int)
    }

    /// Prepares + runs an SQL query and decodes rows into `FoodRow`. Returns
    /// nil on prepare failure (e.g., FTS5 table missing) so the caller can
    /// fall back to an alternative query. Returns `[]` on a successful query
    /// with no matches.
    private func runQuery(sql: String, bindings: [Binding]) -> [FoodRow]? {
        guard let db else { return nil }
        var statement: OpaquePointer?
        defer { sqlite3_finalize(statement) }

        if sqlite3_prepare_v2(db, sql, -1, &statement, nil) != SQLITE_OK {
            return nil
        }
        for (idx, binding) in bindings.enumerated() {
            let position = Int32(idx + 1)
            switch binding {
            case .text(let value):
                // SQLITE_TRANSIENT (-1 cast) tells SQLite to copy the bytes,
                // so the Swift String can be deallocated before step() runs.
                let transient = unsafeBitCast(-1, to: sqlite3_destructor_type.self)
                sqlite3_bind_text(statement, position, value, -1, transient)
            case .int(let value):
                sqlite3_bind_int64(statement, position, Int64(value))
            }
        }

        var rows: [FoodRow] = []
        while sqlite3_step(statement) == SQLITE_ROW {
            rows.append(FoodRow(
                fdcId: Int(sqlite3_column_int64(statement, 0)),
                description: columnText(statement, index: 1) ?? "",
                foodCategory: columnText(statement, index: 2),
                kcalPer100g: columnDouble(statement, index: 3),
                proteinPer100g: columnDouble(statement, index: 4),
                carbsPer100g: columnDouble(statement, index: 5),
                fatPer100g: columnDouble(statement, index: 6),
                sugarPer100g: columnDouble(statement, index: 7),
                addedSugarPer100g: columnDouble(statement, index: 8),
                fiberPer100g: columnDouble(statement, index: 9),
                satFatPer100g: columnDouble(statement, index: 10),
                monoFatPer100g: columnDouble(statement, index: 11),
                polyFatPer100g: columnDouble(statement, index: 12),
                cholesterolMgPer100g: columnDouble(statement, index: 13),
                sodiumMgPer100g: columnDouble(statement, index: 14),
                potassiumMgPer100g: columnDouble(statement, index: 15)
            ))
        }
        return rows
    }

    private func columnText(_ statement: OpaquePointer?, index: Int32) -> String? {
        guard sqlite3_column_type(statement, index) != SQLITE_NULL,
              let cString = sqlite3_column_text(statement, index)
        else { return nil }
        return String(cString: cString)
    }

    private func columnDouble(_ statement: OpaquePointer?, index: Int32) -> Double? {
        guard sqlite3_column_type(statement, index) != SQLITE_NULL else { return nil }
        return sqlite3_column_double(statement, index)
    }

    /// Escapes user-supplied query for safe use as an FTS5 MATCH expression.
    /// FTS5 treats double-quotes as phrase delimiters and bare punctuation as
    /// operators; the safest universal approach is to quote each whitespace-
    /// separated token after stripping anything that isn't alphanumeric.
    private func sanitizedFTSQuery(_ query: String) -> String {
        let tokens = query
            .lowercased()
            .components(separatedBy: .whitespacesAndNewlines)
            .map { $0.unicodeScalars.filter { CharacterSet.alphanumerics.contains($0) }.map(Character.init) }
            .map { String($0) }
            .filter { !$0.isEmpty }
        guard !tokens.isEmpty else { return "" }
        // Wrap each token as a prefix match so "chick" matches "chicken".
        return tokens.map { "\"\($0)\"*" }.joined(separator: " ")
    }
}
